services:
  dashboard:
    build:
      context: .
      dockerfile: ./dashboard/Dockerfile
    image: snowmapper-dashboard:latest
    container_name: snowmapper-dashboard
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - data:/app/data
      - config:/app/config
      - ./logs:/app/logs
    env_file:
      - .env
    environment:
      - DASHBOARD_ENV=aws
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PORT}/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  data:
    name: snowmapper_data
  config:
    name: snowmapper_config

networks:
  default:
    name: snowmapper_network